project: selva-project-1
buckets:
- name: logs-3
  iam_role_name: writer-role-logs-3
  write_prefix: FOOBAR/logs-3/
  prefix: selva-logs-3
- name: logs-4
  iam_role_name: writer-role-logs-4
  write_prefix: FOOBAR/logs-4/
  prefix: selva-logs-4
