# yaml-language-server: $schema=https://raw.githubusercontent.com/selva-k-thoughtworks/constructor/refs/heads/main/config.schema.json
---
project: selva-project-1
buckets:
- name: logs-22
  iam_role_name: writer-role-logs-22
  write_prefix: FOOBAR/logs-22/
  prefix: selva-logs-22
