name: Trigger Infra Deployment

on:
  push:
    branches:
      - main

jobs:
  encode-config:
    runs-on: ubuntu-latest
    outputs:
      config64: ${{ steps.encode.outputs.config64 }}
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3

      - name: Encode config.yaml
        id: encode
        run: |
          base64 config.yaml > encoded.txt
          echo "config64=$(cat encoded.txt)" >> $GITHUB_OUTPUT

  call-workflow:
    needs: encode-config
    uses: selva-k-thoughtworks/self-infra-sample/.github/workflows/triggered-deploy.yml@main
    with:
      config_base64: ${{ needs.encode-config.outputs.config64 }}
    secrets: inherit
    outputs:
      result: ${{ steps.set-result.outputs.result }}  # this must be set inside Repo B's workflow

  print-result:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - name: Print result
        run: echo "Terraform result was: ${{ needs.call-workflow.outputs.result }}"
